### ISSUE TITLE
FRON: Design "My Packages" page

### ISSUE THREAD

**Issue by abdoulrasheed** [BuildForSDGCohort2/Team-97A-Frontend#24]
Left side navigation should not be included in this design;

Ref to: https://www.figma.com/file/PBBod732JBJVihuBgzQeDm/Team97?node-id=0%3A1

**Comment by abdoulrasheed** [comment]
@Deyems, please self-assign this too

**Comment by Deyems** [comment]
@Abdoulrasheed I am not sure what you mean by that
